version: '3'
services:

  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_TLS_ENABLED=no

  vault-dev:
    image: vault:1.2.1
    restart: always
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8233
      VAULT_ADDR: http://127.0.0.1:8233
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports:
      - "28233:8233"
    volumes:
      - ./docker/vault/tmp:/vault/tmp
      - ./docker/vault/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/service_started"]
      timeout: 1s
      retries: 20

